### ISSUE TITLE
support scoring shorter length results higher

### ISSUE THREAD

**Issue by marbemac** [seatgeek/soulmate#18]
I have a large database of topics that users are allowed to search (via soulmate). Each topic has reputation on the website so that translates nicely to a soulmate score. However, when a user types a short word often longer words that include this short word will show up first. For example if the user types 'band', there are many topics in the world with the word band included in their name. I'm not sure what the best way to implement this is, but would it be possible to allow weighting of shorter words higher? Such that if someone searches 'band' the topic 'band' will be more likely to show up than 'dave matthew's band'? Maybe take into account the score as well.

I'm open to all ideas. Thanks!

**Comment by josegonzalez** [comment]
Closing since this is unmaintained. Please use [soulheart](https://github.com/sethherr/soulheart) instead!
