### ISSUE TITLE
The exact match is not the first item of the results

### ISSUE THREAD

**Issue by Ahimta** [seatgeek/soulmate#39]
When I have the following terms in Soulmate:
["Citrix", "Citrix SaaS", "Citrix UK User Group", "Citrix User Group Norway", "Citrix VDI-In-A-Box (Kaviza) User Group", "Dutch Citrix User Group", "Freelancer Citrix Certified Trainer/ Consultant", "Remote Citrix Experts", "SBC Solutions your Citrix solution", "Xenergix - Expertos en Citrix"]

When I search Soulmate using the term "Citrix", I get these terms:
["Citrix SaaS", "Freelancer Citrix Certified Trainer/ Consultant", "Remote Citrix Experts", "Citrix", "SBC Solutions your Citrix solution", "Citrix VDI-In-A-Box (Kaviza) User Group", "Dutch Citrix User Group", "Citrix User Group Norway", "Citrix UK User Group", "Xenergix - Expertos en Citrix"]

Why isn't the exact match the first in the result?

**Comment by josegonzalez** [comment]
Closing since this is unmaintained. Please use [soulheart](https://github.com/sethherr/soulheart) instead!
