### ISSUE TITLE
Use ZRANGEBYLEX to improve memory usage

### ISSUE THREAD

**Issue by antirez** [seatgeek/soulmate#41]
Redis 2.8.9 introduced a new command called [ZRANGEBYLEX](http://redis.io/commands/zrangebylex) that soulmate could use internally to improve performances and reduce memory usage significantly.

An example of implementation of autocomplete using the new command is here: http://autocomplete.redis.org/

Note: sometimes the example is down because I've not enough memory in the virtual machine running the example.

**Comment by josegonzalez** [comment]
Closing since this is unmaintained. Please use [soulheart](https://github.com/sethherr/soulheart) instead!
