### ISSUE TITLE
is it support chinese search?

### ISSUE THREAD

**Issue by JoyCood** [seatgeek/soulmate#45]
is it support chinese search?  like "你好".

**Comment by erwaller** [comment]
Some work has been done to support unicode (https://github.com/seatgeek/soulmate/pull/29), but I'm not sure how well it performers with totally foreign language text

**Comment by josegonzalez** [comment]
Closing since this is unmaintained. Please use [soulheart](https://github.com/sethherr/soulheart) instead!
