### ISSUE TITLE
Is there a plan to support Rails 5?

### ISSUE THREAD

**Issue by jancel** [seatgeek/soulmate#49]
Having massive trouble demangling all the rack, etc. to get this working with Rails 5.  Anyone have a baranch/fork that will offer this support?

**Comment by sethherr** [comment]
I'll make sure that [soulheart](/sethherr/soulheart) supports it in the next few days.

**Comment by sethherr** [comment]
Pushed some fixes https://github.com/sethherr/soulheart/pull/23 - the newest version of Soulheart (0.2.7) works for me on Rails 5 with Ruby 2.2.5

**Comment by benone** [comment]
@jancel I've changed rack/contrib to rack/jsonp: https://github.com/benone/soulmate 
Works with rails 5

**Comment by jancel** [comment]
Thanks.  I'll look at changing to that one.

**Comment by cseeger** [comment]
I wound up using [Soulheart](https://github.com/sethherr/soulheart) instead. Of course, I was forced to update Sinatra to 'rc2', but all is well again. 

GL!

**Comment by josegonzalez** [comment]
Yeah I think the idea here is that... we're not maintaining this anymore. We're no longer maintaining our rails app, and my ruby knowledge more or less stops at chef.

If the soulheart folks want to get commit bit and like... force push onto our repo, I actually wouldn't be opposed to it. A new org for this repo would probably make most sense as well, so its not under our name.

**Comment by sethherr** [comment]
Soulheart isn't completely compatible with Soulmate. I don't think I would want to merge the two together because I'd worry about somebody `bundle update`ing and it breaking things.

I'd vote for just adding a little note to the top of the readme. Something like:

> Soulmate is no longer being actively maintained. For a similar project that is still actively developed, check out [soulheart](https://github.com/sethherr/soulheart)

**Comment by josegonzalez** [comment]
Done and done! Thanks community for being patient with us, and hopefully the soulheart project gets the all the love and attention we've been getting these past few years. Break some hearts!
