### ISSUE TITLE
Rake aborted. LoadError: cannot load such file -- rack/showexceptions

### ISSUE THREAD

**Issue by ShivrajDeepsagar** [seatgeek/soulmate#51]
After running bundle install with gems
gem 'rack-contrib'
gem 'soulmate', :require => 'soulmate/server'
in the gem file of my rails app (5.0.1) I keep getting this

LoadError: cannot load such file -- rack/showexceptions
/var/lib/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
/var/lib/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
/var/lib/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
/var/lib/gems/2.3.0/gems/soulmate-1.1.0/lib/soulmate/server.rb:1:in `require'
/var/lib/gems/2.3.0/gems/soulmate-1.1.0/lib/soulmate/server.rb:1:in `<top (required)>'
/home/shivraj/Projects/fast-autocomplete/config/application.rb:7:in `<top (required)>'
/home/shivraj/Projects/fast-autocomplete/Rakefile:4:in `require_relative'
/home/shivraj/Projects/fast-autocomplete/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
 Error.
after running rake db:migrate. 
Could anybody please tell me what the issue is about?

**Comment by josegonzalez** [comment]
Closing since this is unmaintained. Please use [soulheart](https://github.com/sethherr/soulheart) instead!
