### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by monaco89** [seatgeek/soulmate#52]
This is broken... using autocomplete gets 400 error:
Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400)

{"message":"missing required parameter: q","meta":{"status":400},"status":400}

Probably the word 'term' needs to be changed to 'q'

**Comment by josegonzalez** [comment]
Thats not an error we raise anywhere in soulmate. Also, this project is no longer maintained in favor of [soulheart](https://github.com/sethherr/soulheart).

**Comment by monaco89** [comment]
I'm guessing something changed on the seat geek api end... since it was working recently. Thanks anyways

**Comment by josegonzalez** [comment]
This oss project has nothing to do with the SeatGeek API, and our API has always required the `q` argument for searching.

If you need support for that, please go to our [api support issue tracker](https://github.com/seatgeek/api-support/issues).
